---
- name: Apply Kubernetes Deployment
  hosts: all
  tasks:
    - name: Run kubectl apply command
      shell:
        cmd: kubectl apply -f /home/ubuntu/Deployment.yml;kubectl apply -f /home/ubuntu/Service.yml
        executable: /bin/bash
